# Generated by Django 5.2.8 on 2025-12-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_account_id_booking_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='decive',
            new_name='device',
        ),
    ]
