# Generated by Django 6.0 on 2025-12-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accumulated_cost',
            field=models.FloatField(default=0),
        ),
    ]
