# Generated by Django 6.0 on 2025-12-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_booking_accumulated_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
        migrations.AddField(
            model_name='device',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
