# Generated by Django 6.0 on 2025-12-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_booking_duration_device_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='number',
        ),
    ]
