# Generated by Django 6.0 on 2025-12-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_device_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('Pc', 'pc'), ('Psg', 'psg')]),
        ),
    ]
