# Generated by Django 6.0 on 2025-12-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='device_status',
            field=models.BooleanField(default=False),
        ),
    ]
