# Generated by Django 6.0 on 2025-12-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_booking_device_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='device_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='played_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('Pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
