# Generated by Django 6.0 on 2025-12-19 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_account_password_remove_account_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='accumulated_cost',
            field=models.FloatField(default=0, verbose_name='Accumulated cost'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='played_minutes',
            field=models.IntegerField(default=0, verbose_name='Played minutes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.zone', verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='device',
            name='devices',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Devices'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Is booked'),
        ),
        migrations.AlterField(
            model_name='device',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.room', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='device',
            name='screen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Screen'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('pc', 'PC'), ('psg', 'PSG')], max_length=10, verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='device',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.zone', verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Room name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.zone', verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Zone name'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Total price'),
        ),
    ]
