# Generated by Django 6.0 on 2025-12-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_account_balance_alter_account_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devices/', verbose_name='Image'),
        ),
    ]
