# Generated by Django 6.0 on 2025-12-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_device_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devices/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='zone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devices/', verbose_name='Image'),
        ),
    ]
