# Generated by Django 6.0 on 2025-12-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_room_image_zone_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='zone/', verbose_name='Image'),
        ),
    ]
