# Generated by Django 6.0 on 2025-12-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_room_image_alter_zone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Is booked'),
        ),
    ]
